version: "3.9"

services:
  synthea:
    build: .
    container_name: synthea-generator
    environment:
      PATIENTS: ${PATIENTS:-10}
      MAX_BUNDLE_MB: ${MAX_BUNDLE_MB:-2}
    volumes:
      - ./output:/app/output
